### ISSUE TITLE
Limiting text on slides

### ISSUE THREAD

**Issue by ahuber3** [course-fish274-2020/Hannah-mussels#2]
You should try subsetting your "post" and "pre" values for your histogram! It'll help make it a little easier to analyze the Type values side by side

**Comment by hpikel** [comment]
I'm a little confused by what you mean by subsetting? Could you explain a bit more? I am struggling with making this graph in general so any help would be much appreciated! Thanks!

**Comment by hpikel** [comment]
Actually I think I figured it out! Thanks again.
